theme: jekyll-theme-dinky
title: [Stan]
description: [![Contribution](https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat)](https://github.com/epidemiology-stan/epidemiology-stan.github.io)
